### ISSUE TITLE
kaputt

### ISSUE THREAD

**Issue by heisig** [kiliankoe/arbeitszeitnachweis#10]
das Ding ist putt, füllt nicht mehr automatisch aus :(

**Comment by kiliankoe** [comment]
@sebastian!!!

**Comment by heisig** [comment]
(╯°□°）╯︵ uɐıʇsɐqǝS

**Comment by sjmielke** [comment]
Na der Berliner Herr Eide wird sich über den Mention freuen :D Schöne Grüße!

Zum Thema: hatten wir nicht schon rausgefunden, dass es jetzt nur noch im Firefox geht, weil Chrome oder ich keine Webstandards können oder so?^^

**Comment by kiliankoe** [comment]
Oh. Ähm. Entschuldigung @sebastian :D

Mensch Sebastian, mach ma wieder ganz hier! :D

**Comment by sjmielke** [comment]
Chrome kann halt kein for .. of über der NodeList, das ist irgendwie ziemlich doof.
Ich forms in ne Zählvariablenschleife aus dem letzten Jahrtausend um und pushe es dann...

**Comment by JustusAdam** [comment]
Tja, mit coffeescript wäre das nicht passiert ...
