### ISSUE TITLE
Falsche Berechnung der Stunden

### ISSUE THREAD

**Issue by mushruptor** [kiliankoe/arbeitszeitnachweis#19]
Mir ist wiederholt aufgefallen, dass die Stundenberechnung etwas rumbugged. Gefährlich, wenn man nicht probeliest. Ein Beispiel:

Kommen 13:00
Gehen 16:00
Arbeitszeit 2h

Es wird manchmal nach oben, manchmal nach unten gerundet. Allerdings nicht wie bei halben Stunden, dass es am Monatsende stimmt, sondern häufig ist man 2h zu wenig oder 2h zu viel da.

**Comment by kiliankoe** [comment]
Hi Marcel 👋 

Die Zeitspannen sind in der Tat manchmal größer als die Arbeitsstunden für den jeweiligen Tag. Das soll so, passend zur Fußnote 3:

> Berechnungsbeispiel: Kommen: 8:00 Uhr, Gehen: 16:00 Uhr, tats. Tätigkeit: 10:00 - 12:00 Uhr u. 13:00 - 14:00 Uhr => einzutragen bei tats. Arbeitszeit: 3 h

Weniger sollte es allerdings hoffentlich nie sein 🙈 Das wäre tatsächlich ein Bug.
