### ISSUE TITLE
Gehen-Werte falsch

### ISSUE THREAD

**Issue by Philipp97714** [kiliankoe/arbeitszeitnachweis#21]
Bei der Einstellungen Gleichmäßig wird der Wert bei Gehen falsch berechnet

**Comment by kiliankoe** [comment]
Hi Philipp, meinst du das gleiche wie #19? Das ist tatsächlich ein Feature, kein Bug.

**Comment by Philipp97714** [comment]
Hi Kilian, Nein, das meine ich:
![image](https://user-images.githubusercontent.com/12154508/66258991-17ba7e80-e7ac-11e9-9b7a-6b3902375cd5.png)

**Comment by kiliankoe** [comment]
Huch, das ist ja spannend, hab ich auch noch nicht gesehen 🙈

**Comment by Philipp97714** [comment]
@kiliankoe merkt man ja normal auch nicht, es sei denn man arbeitet am SWT Lehrstuhl, denn dort muss man tatsächlich die Stundenzettel gleichmäßig ausfüllen

**Comment by kiliankoe** [comment]
Kannst du das jetzt mit dem Fix von @pixix4 in #22 nochmal probieren?

**Comment by Philipp97714** [comment]
fixed in #22
